//
// Created by Yuanmin Miao on 2026-03-05.
//

#include "DOGCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()

#include <itkImage.h>
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <itkSmoothingRecursiveGaussianImageFilter.h>
#include <itkSubtractImageFilter.h>
#include <itkRescaleIntensityImageFilter.h>
#include <iostream>

int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h

  // 1. Set reader
  using PixelType = float;
  using OutputPixelType = unsigned char;
  constexpr unsigned int Dimension = 3;
  using ImageType = itk::Image<PixelType, Dimension>;
  using OutputImageType = itk::Image<OutputPixelType, Dimension>;

  // 2. Set reader
  using ReaderType = itk::ImageFileReader<ImageType>;
  auto reader = ReaderType::New();
  reader->SetFileName(input);

  // 3. Set filter
  using FilterType = itk::SmoothingRecursiveGaussianImageFilter<ImageType, ImageType>;

  auto filter1 = FilterType::New();
  auto filter2 = FilterType::New();
  auto subtract = itk::SubtractImageFilter<ImageType, ImageType, ImageType>::New();

  filter1->SetInput(reader->GetOutput());
  filter1->SetSigma(sigma1);
  filter2->SetInput(reader->GetOutput());
  filter2->SetSigma(sigma2);
  subtract->SetInput1(filter1->GetOutput());
  subtract->SetInput2(filter2->GetOutput());

  // 4. Set writer
  using RescaleFilterType = itk::RescaleIntensityImageFilter<ImageType, OutputImageType>;
  auto rescaler = RescaleFilterType::New();
  rescaler->SetInput(subtract->GetOutput());
  rescaler->SetOutputMinimum(0);
  rescaler->SetOutputMaximum(255);

  // 5. Set writer
  using WriterType = itk::ImageFileWriter<OutputImageType>;
  auto writer = WriterType::New();
  writer->SetFileName(output);
  writer->SetInput(rescaler->GetOutput());

  // 6. Execute pipeline and catch exceptions
  try
  {
    writer->Update();
  }
  catch (const itk::ExceptionObject & e)
  {
    std::cerr << "Error: " << e << std::endl;
    return EXIT_FAILURE;
  }

  std::cout << "The input volume is: " << input << std::endl;
  std::cout << "The output volume is: " << output << std::endl;
  return EXIT_SUCCESS;
}
