//
// Created by Yuanmin Miao on 2026-03-05.
//

#include "GaussianLPFCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()

#include <itkImage.h>
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <itkRecursiveGaussianImageFilter.h>
#include <iostream>

int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h

  // 1. Set reader
  using PixelType = float;
  constexpr unsigned int Dimension = 3;
  using ImageType = itk::Image<PixelType, Dimension>;

  // 2. Set reader
  using ReaderType = itk::ImageFileReader<ImageType>;
  auto reader = ReaderType::New();
  reader->SetFileName(input);

  // 3. Set filter
  using FilterType = itk::RecursiveGaussianImageFilter<ImageType, ImageType>;

  auto filterX = FilterType::New();
  auto filterY = FilterType::New();
  auto filterZ = FilterType::New();

  filterX->SetInput(reader->GetOutput());
  filterX->SetDirection(0);
  filterX->SetSigma(sigma);

  filterY->SetInput(filterX->GetOutput());
  filterY->SetDirection(1);
  filterY->SetSigma(sigma);

  filterZ->SetInput(filterY->GetOutput());
  filterZ->SetDirection(2);
  filterZ->SetSigma(sigma);

  // 4. Set writer
  using WriterType = itk::ImageFileWriter<ImageType>;
  auto writer = WriterType::New();
  writer->SetFileName(output);
  writer->SetInput(filterZ->GetOutput());

  // 5. Execute pipeline and catch exceptions
  try
  {
    writer->Update();
  }
  catch (const itk::ExceptionObject & e)
  {
    std::cerr << "Error: " << e << std::endl;
    return EXIT_FAILURE;
  }

  std::cout << "The input volume is: " << input << std::endl;
  std::cout << "The output volume is: " << output << std::endl;
  return EXIT_SUCCESS;
}
